name: Deploy para Firebase Hosting

on:
  push:
    branches:
      - main  # ou a branch que você deseja acionar o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Especifique a versão do Node.js que você usa

    - name: Instalar dependências
      run: npm ci

    - name: Construir projeto
      run: npm run build

    - name: Fazer deploy para o Firebase
      uses: FirebaseExtended/action-hosting-deploy@v1
      with:
        project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
        token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
